// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB53VTvux1oq6pY7dZRxyOaj9AyhQlBuqo',
    appId: '1:1042281760058:web:f39a5ba12eb798a0693c03',
    messagingSenderId: '1042281760058',
    projectId: 'tcg-testing',
    authDomain: 'tcg-testing.firebaseapp.com',
    storageBucket: 'tcg-testing.appspot.com',
    measurementId: 'G-KB88298F1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoypDtFuYFkZZ1r2JGE2vI9R2XmNqOrAg',
    appId: '1:1042281760058:android:4b850ee44707b449693c03',
    messagingSenderId: '1042281760058',
    projectId: 'tcg-testing',
    storageBucket: 'tcg-testing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6aOYY1oDSpHyJjoCFTJ6zPnWvTMTviA0',
    appId: '1:1042281760058:ios:6f7990863481e019693c03',
    messagingSenderId: '1042281760058',
    projectId: 'tcg-testing',
    storageBucket: 'tcg-testing.appspot.com',
    iosBundleId: 'com.example.app',
  );
}
